### ISSUE TITLE
Should we add GitHub workflows for ...

### ISSUE THREAD

**Issue by ralfhandl** [OAI/Overlay-Specification#53]
- [x] Markdown validation
  * Similar to / copy of https://github.com/OAI/OpenAPI-Specification/blob/main/.github/workflows/validate-markdown.yaml
  * #51
- [x] Respeced HTML generation
  * #55
- Agenda creation
  - This might be a bit trickier as there is no copy template 😎 
  - OAS and Arazzo use agenda _issues_ which can be modified using the `gh` CLI and have a workflow using it
  - Moonwalk and Overlay use agenda _discussions_ which can't be modified via the `gh` CLI and don't have a workflow
  - There's a [GraphQL API for Discussions](https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions) that allows to create new discussions and does not allow to pin or unpin a discussion, so someone would have to pin new and unpin past discussions

**Comment by lornajane** [comment]
Yes please, to all of these. For the markdown, do we want to run the whole reformatting/validating thing at pull request time so like prettier and whatever, or just mdv? I think I'd use markdownlint instead of mdv now, since it's markdownlint we use in the build process

**Comment by ralfhandl** [comment]
Markdownlint is not a superset of mdv, mdv for example catches syntax errors in YAML code blocks.

And mdv is not a superset of markdownlint, so maybe we want to use both?
