### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by ralfhandl** [OAI/Overlay-Specification#59]
- [x] Review Respec preview at https://ralfhandl.github.io/OpenAPI-Specification/overlay/v1.0.0.html
  - [x] Add first section "Abstract" and use it in ReSpec instead of repeating the "Introduction"
    - #60
  - [x] #61
  - [x] #62
- [x] Add Publication Date for 1.0.0 in version table of 1.0.0.md
- [x] Update respec build script to create PRs in the official OAI/OpenAPI-Specification repo
  - #84
- [x] Update OAS_REPO_TOKEN in https://github.com/OAI/Overlay-Specification/settings/secrets/actions

**Comment by notEthan** [comment]
In the preview, the sections "What is the Overlay Specification?" and "2. Introduction" repeat each other.
This does seem to be intentional, looking at md2html.js, but I don't know why it would be desirable to repeat these paragraphs.

**Comment by ralfhandl** [comment]
> why it would be desirable to repeat these paragraphs

It is not, it actually is desirable to have an explicit "Abstract" in the markdown document that can be used as the required ReSpec abstract.
