### ISSUE TITLE
Overlays Meeting - Tuesday 5 October 2021

### ISSUE THREAD

**Issue by webron** [OAI/Overlay-Specification#6]
**NOTE: This meeting is on Tuesday at 9am - 10am PT**

Zoom Meeting link: [https://zoom.us/j/97548445391](https://zoom.us/j/97548445391). 

[Code-of-Conduct](https://github.com/OAI/OpenAPI-Specification/blob/main/CODE_OF_CONDUCT.md#code-of-conduct)

We'll use this opportunity to discuss current issues with the Overlay Specification and decide on next steps.

![F10B5460-B4B3-4463-9CDE-C7F782202EA9](https://user-images.githubusercontent.com/21603/121568843-0b260900-ca18-11eb-9362-69fda4162be8.jpeg)
(The above is taken from the regular TDC weekly meetings, but will be applied to this meeting as well)

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| | | |
JMESPath, JsonPath and others |  | |

**Comment by kevinswiber** [comment]
Related to the query syntax: https://github.com/OAI/Overlay-Specification/issues/7

**Comment by webron** [comment]
Meeting recording - https://zoom.us/rec/share/7sbE_hdozNcZ-3BI6cs0Y-BG_4bAC2O1Km3kHtkYmQnTdelVgB4kZgb9d0JFFbOu.ejcPoy1oiMFnEUkJ?startTime=1633449931000
