### ISSUE TITLE
Does `update` use "deep merge" or "shallow merge"?

### ISSUE THREAD

**Issue by ralfhandl** [OAI/Overlay-Specification#61]
The [Action Object](https://github.com/OAI/Overlay-Specification/blob/main/versions/1.0.0.md#action-object) definition currently states that

> properties in the merge object _replace_ properties in the target object with the same name

If that is to be the case, then the [Structured Overlays Example](https://github.com/OAI/Overlay-Specification/blob/main/versions/1.0.0.md#structured-overlays-example) would _replace_ existing path item objects with sparse and incomplete objects, containing only an incomplete operation object for GET, missing for example the required `responses` field.

The "Structured Overlays Example" will only work if nested objects within the `update` object are also merged with their counterpart in the target, recursively. Nested arrays would still have to replace their counterpart in the target, same as primitive values.

**Comment by ralfhandl** [comment]
[Experiments](https://github.com/ralfhandl/Overlay-Specification/tree/junk/examples/examples):
* [bump-sh](https://github.com/bump-sh/cli) uses "deep merge" instead of "replace"
* [speakeasy](https://www.speakeasy.com/docs/speakeasy-cli/getting-started) uses "deep merge" instead of "replace"

**Comment by lornajane** [comment]
The wording isn't accurate but the tools seem to do a good and expected thing.

Suggested wording:

When the Overlay document is applied, the properties in the `update` object are recursively merged with the properties in the target object with the same names; new properties are added to the target object.
