### ISSUE TITLE
📣 Voting for 1.0.0 release approval

### ISSUE THREAD

**Issue by lornajane** [OAI/Overlay-Specification#69]
The OpenAPI Overlay Specification is ready for release. In order for this to happen, 2/3 of the @OAI/tsc must "vote" to approve the release of the new specification.

Since it's the first release of the specification, there's no big merge PR for the new version - everything is on the `main` branch.
 - read the [Overlay 1.0.0 specification](https://github.com/OAI/Overlay-Specification/blob/main/versions/1.0.0.md)
 - check the release notes in the draft release on the [releases page](https://github.com/OAI/Overlay-Specification/releases)

Please add your approval in the form of a comment on this issue.

**Comment by ralfhandl** [comment]
Approved

**Comment by mikekistler** [comment]
I approve this release.

**Comment by lornajane** [comment]
I also approve this release!

**Comment by lornajane** [comment]
Vote CLOSED. Further changes were made to the specification so we'll need to restart the vote - there are other changes that are ready to include as well so let's stop, regroup, and then decide if we want to retry.

**Comment by mikekistler** [comment]
I approve!

**Comment by ralfhandl** [comment]
I approve the modified version 1.0.0

**Comment by earth2marsh** [comment]
Approved

**Comment by miqui** [comment]
I am good.

**Comment by darrelmiller** [comment]
Approved

**Comment by lornajane** [comment]
Re-opened now that the spec is updated

**Comment by lornajane** [comment]
Also I approve!

**Comment by swaldron58** [comment]
Approve

**Comment by lornajane** [comment]
Released! I'll close this issue.
