### ISSUE TITLE
consistency on the naming of Overlay / Overlays

### ISSUE THREAD

**Issue by jeremyfiel** [OAI/Overlay-Specification#73]
I think the official name is `Overlay` but there are quite a few references to `Overlays` (plural) in the specification and readme.md

If they are references to an Overlay description, I believe they should be lowercase or reworded.

https://github.com/OAI/Overlay-Specification/blob/d029f0d7d2c8861e00de4467ab795e86d9e35824/versions/1.0.0.md?plain=1#L137

https://github.com/OAI/Overlay-Specification/blob/d029f0d7d2c8861e00de4467ab795e86d9e35824/versions/1.0.0.md?plain=1#L165

https://github.com/OAI/Overlay-Specification/blob/d029f0d7d2c8861e00de4467ab795e86d9e35824/versions/1.0.0.md?plain=1#L188

https://github.com/OAI/Overlay-Specification/blob/d029f0d7d2c8861e00de4467ab795e86d9e35824/README.md?plain=1#L20

https://github.com/OAI/Overlay-Specification/blob/d029f0d7d2c8861e00de4467ab795e86d9e35824/README.md?plain=1#L22

**Comment by ralfhandl** [comment]
Hi @jeremyfiel,

Thanks for reporting this!

Would it be sufficient to address this in the next release?

Thanks in advance!

**Comment by lornajane** [comment]
Since voting is already open after many rounds of feedback, the specification itself is closed for changes. We can definitely pick it up for a future patch release though.

**Comment by jeremyfiel** [comment]
> Would it be sufficient to address this in the next release?

Sure!

**Comment by ralfhandl** [comment]
@jeremyfiel Since we have som other pending changes I tried to address your concerns in
* #78 

Rationale: the specification defines
> An Overlay is a JSON or YAML structure containing an ordered list of [Action Objects](https://ralfhandl.github.io/OpenAPI-Specification/overlay/v1.0.0.html#overlay-actions) that are to be applied to the target document.

Thus the use of "Overlay" in the section headlines and the README text seems justified.

**Comment by jeremyfiel** [comment]
@ralfhandl  this should be updated to 1.0.0 release milestone 

thanks for your follow up!
