### ISSUE TITLE
Add `examples` directory

### ISSUE THREAD

**Issue by earth2marsh** [OAI/Overlay-Specification#82]
As a tooling developer looking to implement overlays, I would like to have at least one example of a well-formed overlay, original description document, and a merged result. Today I would have to build my own examples from the in-line examples of the Overlays Specification.

Here is a quick gist that shows what I mean: https://gist.github.com/earth2marsh/51689e3b93d1140dec75a381fa9989ef

(and happy to add this directory and files via a PR if that helps!)

**Comment by handrews** [comment]
We recently decided to remove the `examples` directory from the OAS repo, and we should align with that for Overlay.  It was a problem to have our GitHub directory and branch structure be part of our "public" interface.

Please instead update the specification to point to the Learn site, which is where we moved the [OAS examples](https://learn.openapis.org/examples/) (which are now rendered nicely and can have commentary with them as well!)

**Comment by lornajane** [comment]
I'm closing this request in favour of adding documentation to the learn site. The work in #99 might also be interesting/relevant.
