### ISSUE TITLE
Adjust respec workflow behaviour for forks

### ISSUE THREAD

**Issue by lornajane** [OAI/Overlay-Specification#91]
We recently added a respec workflow but it requires a token, and therefore fails on my fork where it does not have one. Could we either make it only work on this repository, or otherwise fail more elegantly for contributors on forks?

**Comment by handrews** [comment]
@lornajane I think this only happens for older forks and GitHub has since changed the default to not run actions on forks.  There's an article about fixing it for older forks: https://github.com/orgs/community/discussions/26704

**Comment by ralfhandl** [comment]
With #93 the workflow will skip its only job in a fork:

![image](https://github.com/user-attachments/assets/39dc3270-53ba-46a4-9c39-3120028d52cb)


You can additionally disable the `respec` workflow in your fork to avoid those grey "do nothing" runs:

![image](https://github.com/user-attachments/assets/da3436cd-80e2-4a90-89d8-88d388f53bfe)

With #93 this will no
